(() => {
  const STORAGE_KEY="container-booking-production-v1";
  const roles={service:{label:"客服",defaultView:"dashboard"},ops:{label:"运营",defaultView:"ops-dashboard"},warehouse:{label:"仓库",defaultView:"warehouse-calendar"},it:{label:"后台 IT",defaultView:"it-dashboard"}};
  const navItems={
    service:[["dashboard","▦","预约总览"],["containers","▤","货柜清单"],["booking","＋","发起预约"],["customers","◎","客户管理"],["warehouses","⌂","仓库管理"]],
    ops:[["ops-dashboard","▦","运营看板"],["audit","✓","预约审核"],["slots","◷","Slot 配置"],["super","⚡","超级预约"]],
    warehouse:[["warehouse-calendar","□","仓库日历"],["warehouse-tasks","▤","作业清单"]],
    it:[["it-dashboard","◆","系统总览"],["containers","▤","货柜清单"],["customers","◎","客户管理"],["warehouses","⌂","仓库管理"],["audit","✓","预约审核"],["slots","◷","Slot 配置"],["super","⚡","超级预约"],["warehouse-calendar","□","仓库日历"],["warehouse-tasks","▤","作业清单"],["accounts","♙","账号管理"]]
  };
  const statusMap={draft:["待预约","neutral"],pending:["待运营审核","wait"],reschedule_pending:["待客服确认","info"],confirmed:["已预约","ok"],arrived:["已到场","info"],completed:["已完成卸货","ok"],rejected:["已拒绝","bad"],customer_rejected:["客服拒绝改期","bad"],cancelled:["已取消","neutral"]};
  const occupiedStatuses=["reschedule_pending","confirmed","arrived","completed"],activeStatuses=["pending",...occupiedStatuses];
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const pad=n=>String(n).padStart(2,"0"),iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
  const plusDays=n=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+n);return iso(d)};
  const cnDate=v=>{const d=new Date(`${v}T12:00:00`);return `${d.getMonth()+1}月${d.getDate()}日`},cnDateLong=v=>{const d=new Date(`${v}T12:00:00`);return `${d.getFullYear()}年${d.getMonth()+1}月${d.getDate()}日`};
  const nowText=()=>new Date().toLocaleString("zh-CN",{hour12:false}),uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`;
  function seed(){
    return {version:4,warehouses:[],customers:[],containers:[],slots:[],bookings:[],dailyCaps:{},dailyLimits:{},accounts:[],logs:[]};
  }
  function migrate(raw){const fresh=seed(),d=raw||fresh;d.version=4;d.logs=d.logs||[];d.dailyCaps=d.dailyCaps||{};d.dailyLimits=d.dailyLimits||{};d.accounts=[];d.warehouses=(d.warehouses||[]).map(w=>({active:true,defaultDailyTotal:20,...w}));d.customers=(d.customers||[]).map(c=>({active:true,defaultDailyMax:6,...c}));d.containers=d.containers||[];d.slots=d.slots||[];d.bookings=d.bookings||[];d.bookings.forEach(b=>b.history=b.history||[]);return d}
  let data;try{data=migrate(JSON.parse(localStorage.getItem(STORAGE_KEY)))}catch{data=seed()}
  let session={role:null,user:null,token:sessionStorage.getItem("container-session-token")||"",view:null,filters:{warehouse:"all",customer:"all",query:"",statuses:["draft","reschedule_pending"]},statusMenuOpen:false,selectedDate:plusDays(0),superSelected:null};
  let suppressCloudSave=false,syncTimer=null,cloudPollTimer=null,lastCloudUpdate="";
  function sharedState(){const {accounts,...state}=data;return state}
  const API_ORIGIN=location.hostname.endsWith(".gitee.io")?"https://container-booking-d6doib212e061e-1494951598.ap-shanghai.app.tcloudbase.com":"";
  async function api(path,options={}){const response=await fetch(`${API_ORIGIN}${path}`,{headers:{"Content-Type":"application/json",...(session.token?{Authorization:`Bearer ${session.token}`}:{}) ,...(options.headers||{})},...options});let payload={};try{payload=await response.json()}catch{}if(!response.ok)throw new Error(payload.error||"云端服务暂时不可用");return payload}
  async function pushState(){if(!session.user)return;const payload=await api("/api/state",{method:"PUT",body:JSON.stringify({state:sharedState()})});lastCloudUpdate=payload.updatedAt||lastCloudUpdate;return payload}
  const save=()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(data));if(session.user&&!suppressCloudSave){clearTimeout(syncTimer);syncTimer=setTimeout(()=>{syncTimer=null;pushState().catch(error=>toast(`云端同步失败：${error.message}`))},250)}};
  async function refreshState(){const payload=await api("/api/state"),accounts=data.accounts||[];suppressCloudSave=true;data=migrate(payload.state||seed());data.accounts=accounts;lastCloudUpdate=payload.updatedAt||"";localStorage.setItem(STORAGE_KEY,JSON.stringify(data));suppressCloudSave=false;return data}
  async function pollCloudState(){if(!session.user||syncTimer)return;try{const payload=await api("/api/state");if(payload.updatedAt&&payload.updatedAt!==lastCloudUpdate){const accounts=data.accounts||[];suppressCloudSave=true;data=migrate(payload.state||seed());data.accounts=accounts;lastCloudUpdate=payload.updatedAt;localStorage.setItem(STORAGE_KEY,JSON.stringify(data));suppressCloudSave=false;render();toast("已同步最新预约数据")}}catch{}}
  function startCloudPolling(){clearInterval(cloudPollTimer);cloudPollTimer=setInterval(pollCloudState,30000)}
  async function refreshAccounts(){const payload=await api("/api/accounts");data.accounts=payload.accounts||[];save();return data.accounts}
  const warehouse=id=>data.warehouses.find(x=>x.id===id),customer=code=>data.customers.find(x=>x.code===code),container=id=>data.containers.find(x=>x.id===id),slot=id=>data.slots.find(x=>x.id===id);
  const isContainerVisible=c=>!!c&&customer(c.customer)?.active!==false&&warehouse(c.warehouse)?.active!==false&&!!customer(c.customer)&&!!warehouse(c.warehouse);
  const bookingForContainer=id=>[...data.bookings].reverse().find(b=>b.containerId===id&&activeStatuses.includes(b.status)),bookingCount=id=>data.bookings.filter(b=>b.slotId===id&&occupiedStatuses.includes(b.status)).length,remaining=s=>s.capacity-bookingCount(s.id);
  const dailyKey=(w,d)=>`${w}|${d}`,limitKey=(w,d,c)=>`${w}|${d}|${c}`;
  const dailyCount=(w,d)=>data.bookings.filter(b=>occupiedStatuses.includes(b.status)&&container(b.containerId)?.warehouse===w&&slot(b.slotId)?.date===d).length;
  const customerDayCount=(w,d,c)=>data.bookings.filter(b=>occupiedStatuses.includes(b.status)&&container(b.containerId)?.warehouse===w&&container(b.containerId)?.customer===c&&slot(b.slotId)?.date===d).length;
  const dailyCap=(w,d)=>Number(data.dailyCaps[dailyKey(w,d)]??warehouse(w)?.defaultDailyTotal??999),customerLimit=(w,d,c)=>Number(data.dailyLimits[limitKey(w,d,c)]??customer(c)?.defaultDailyMax??999);
  function capacityDecision(c,s){if(remaining(s)<=0)return {ok:false,reason:"该 Slot 已满"};if(dailyCount(c.warehouse,s.date)>=dailyCap(c.warehouse,s.date))return {ok:false,reason:"当日总预约量已满"};if(customerDayCount(c.warehouse,s.date,c.customer)>=customerLimit(c.warehouse,s.date,c.customer))return {ok:false,reason:"该客户当日预约量已达上限"};return {ok:true,reason:"Slot、当日总量和客户限额均有余量"}}
  function badge(status,isSuper=false){const m=statusMap[status]||[status,"neutral"];return `<span class="badge ${isSuper?"super":m[1]}">${isSuper?"超级预约":m[0]}</span>`}
  function slotBadge(s){const rem=remaining(s);return !s.active?'<span class="badge neutral">已停用</span>':rem>0?'<span class="badge ok">可预约</span>':'<span class="badge wait">已满</span>'}
  function log(action,detail){data.logs.unshift({action,detail,time:nowText(),role:session.role,user:session.user?.name||"系统"});data.logs=data.logs.slice(0,200)}
  function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2600)}
  function closeModal(){$("#modal").classList.add("is-hidden");$("#modal").innerHTML=""}function closeDrawer(){$("#drawer").classList.add("is-hidden");$("#drawer").innerHTML=""}
  function openModal(title,body,footer="",wide=false){const el=$("#modal");el.innerHTML=`<section class="modal ${wide?"wide":""}" role="dialog" aria-modal="true"><header class="modal-head"><h2>${esc(title)}</h2><button class="close" onclick="App.closeModal()">×</button></header><div class="modal-body">${body}</div>${footer?`<footer class="modal-foot">${footer}</footer>`:""}</section>`;el.classList.remove("is-hidden")}
  function options(items,selected,allLabel){return `${allLabel?`<option value="all">${esc(allLabel)}</option>`:""}${items.map(x=>`<option value="${esc(x.value)}" ${x.value===selected?"selected":""}>${esc(x.label)}</option>`).join("")}`}
  function setHeader(t,s,a=""){$("#page-title").textContent=t;$("#page-subtitle").textContent=s;$("#page-actions").innerHTML=a}
  const stat=(l,v,n,c="")=>`<article class="stat"><span class="stat-label">${l}</span><strong class="stat-value">${v}</strong><span class="stat-note ${c}">${n}</span></article>`;
  function clearError(id){const e=$(id);if(!e)return;e.classList.remove("input-invalid");e.closest(".field")?.querySelector(".field-error")?.remove()}
  function fieldError(id,msg){const e=$(id);if(e){clearError(id);e.classList.add("input-invalid");const p=document.createElement("span");p.className="field-error";p.textContent=msg;e.closest(".field")?.appendChild(p);e.focus()}toast(msg);return false}
  const val=id=>$(id)?.value?.trim()||"";
  function showLogin(){$("#app").classList.add("is-hidden");$("#login-screen").classList.remove("is-hidden");$("#login-screen").innerHTML=`<section class="login-card-wrap login-only"><div class="login-card"><div class="login-brand"><span class="brand-mark">箱</span><strong>货柜预约调度台</strong></div><h2>登录工作台</h2><p>请输入系统账号和密码。</p><div class="login-fields"><div class="field"><label>账号</label><input id="login-account" class="input" placeholder="请输入账号" autocomplete="username"></div><div class="field"><label>密码</label><input id="login-password" class="input" type="password" placeholder="请输入密码" autocomplete="current-password" onkeydown="if(event.key==='Enter') App.login()"></div></div><button class="btn primary login-btn" onclick="App.login()">登录工作台</button></div></section>`}
  async function login(){const account=val("#login-account"),password=$("#login-password")?.value||"",button=$(".login-btn");if(!account)return fieldError("#login-account","请输入账号");if(!password)return fieldError("#login-password","请输入密码");button.disabled=true;button.textContent="正在登录…";try{const payload=await api("/api/auth/login",{method:"POST",body:JSON.stringify({account,password})}),a=payload.user;session.token=payload.token||"";sessionStorage.setItem("container-session-token",session.token);session.user=a;session.role=a.role;session.view=roles[a.role]?.defaultView||"dashboard";await refreshState();if(a.role==="it")await refreshAccounts();else data.accounts=[];log("账号登录",a.account);save();startCloudPolling();$("#login-screen").classList.add("is-hidden");$("#app").classList.remove("is-hidden");renderShell();render()}catch(error){session.token="";sessionStorage.removeItem("container-session-token");toast(error.message)}finally{if(button){button.disabled=false;button.textContent="登录工作台"}}}
  async function logout(){try{clearTimeout(syncTimer);syncTimer=null;await pushState();await api("/api/auth/logout",{method:"POST",body:"{}"})}catch{}clearInterval(cloudPollTimer);cloudPollTimer=null;session.role=null;session.user=null;session.token="";sessionStorage.removeItem("container-session-token");data.accounts=[];localStorage.setItem(STORAGE_KEY,JSON.stringify(data));showLogin()}
  function renderShell(){const r=roles[session.role];$("#role-pill").textContent=`当前岗位 · ${r.label}`;$("#nav").innerHTML=navItems[session.role].map(([view,icon,label])=>`<button class="${session.view===view?"active":""}" onclick="App.go('${view}')"><span class="nav-icon">${icon}</span>${label}${view==="audit"&&pendingCount()?`<span class="count-chip">${pendingCount()}</span>`:""}</button>`).join("");$("#profile-button").innerHTML=`<strong>${esc(session.user?.name)} · ${r.label}</strong><span>点击退出或切换账号</span>`;$("#profile-button").onclick=logout}
  async function go(view){session.view=view;$(".sidebar").classList.remove("open");if(view==="accounts"&&session.role==="it"){try{await refreshAccounts()}catch(error){toast(error.message)}}renderShell();render()}
  const pendingCount=()=>data.bookings.filter(b=>b.status==="pending"&&isContainerVisible(container(b.containerId))).length,activeBookings=()=>data.bookings.filter(b=>activeStatuses.includes(b.status)&&isContainerVisible(container(b.containerId)));
  function render(){if(!session.role){showLogin();return}const views={dashboard:renderDashboard,containers:renderContainers,booking:renderBookingCenter,customers:renderCustomers,warehouses:renderWarehouses,"ops-dashboard":renderOpsDashboard,audit:renderAudit,slots:renderSlots,super:renderSuperView,"warehouse-calendar":renderWarehouseCalendar,"warehouse-tasks":renderWarehouseTasks,"it-dashboard":renderITDashboard,accounts:renderAccounts};(views[session.view]||views[roles[session.role].defaultView])()}

  function renderDashboard(){const today=plusDays(0),primary=data.warehouses.find(x=>x.active),confirmed=activeBookings().filter(b=>slot(b.slotId)?.date===today),waiting=activeBookings().filter(b=>b.status==="reschedule_pending"),completed=activeBookings().filter(b=>b.status==="completed");setHeader("预约总览",`${cnDateLong(today)} · 可查看全部客户`,`<button class="btn" onclick="App.openImport()">导入货柜</button><button class="btn primary" onclick="App.openAddContainer()">＋ 新增货柜</button>`);const dates=primary?[0,1,2,3,4].map(n=>dateCard(plusDays(n),primary.id)).join(""):"";$("#view").innerHTML=`<section class="stat-grid">${stat("今日预约",confirmed.length,"全部仓库")}${stat("待运营审核",pendingCount(),"满额或触发限额","hot")}${stat("待客服确认",waiting.length,"已临时占用 Slot")}${stat("已完成卸货",completed.length,"累计完成","good")}</section><section class="grid-2"><div class="panel"><div class="panel-head"><div><h2>近期可预约日期</h2><p>${primary?`${esc(primary.name)} · 日期直接显示可预约余量`:"请先创建并启用仓库"}</p></div><button class="btn small" onclick="App.go('booking')">查看全部</button></div>${primary?`<div class="date-strip">${dates}</div>`:'<div class="empty"><strong>尚未创建仓库</strong>请由后台 IT 或客服先维护仓库资料。</div>'}<div class="panel-head"><h2>最近预约任务</h2><p>全客户数据</p></div>${bookingTable(activeBookings().slice(0,6),true)}</div>${primary?slotPanel(primary.id,today):'<aside class="panel"><div class="empty"><strong>暂无 Slot</strong>创建仓库后可配置预约时段。</div></aside>'}</section>`}
  function statusSummary(){const selected=session.filters.statuses||[];if(selected.length===Object.keys(statusMap).length)return "全部预约状态";if(selected.length<=2)return selected.map(s=>statusMap[s]?.[0]).filter(Boolean).join("、")||"预约状态";return `已选 ${selected.length} 个状态`}
  function statusFilterControl(){const selected=session.filters.statuses||[],all=selected.length===Object.keys(statusMap).length;return `<details class="status-filter" ${session.statusMenuOpen?"open":""} ontoggle="App.statusMenuToggled(this.open)"><summary class="select">${esc(statusSummary())}<span>⌄</span></summary><div class="status-menu"><label class="status-all"><input type="checkbox" ${all?"checked":""} onchange="App.toggleStatus('all',this.checked)">全部预约状态</label>${Object.entries(statusMap).map(([key,m])=>`<label><input type="checkbox" ${selected.includes(key)?"checked":""} onchange="App.toggleStatus('${key}',this.checked)">${esc(m[0])}</label>`).join("")}</div></details>`}
  function renderContainers(onlyAvailable=false){setHeader(onlyAvailable?"发起预约":"货柜清单",onlyAvailable?"选择未预约货柜，并查看日期是否可约或已满":"默认显示待预约和待客服确认的货柜，可多选状态组合筛选",`<button class="btn" onclick="App.openImport()">导入货柜</button><button class="btn primary" onclick="App.openAddContainer()">＋ 新增货柜</button>`);const f=session.filters,selected=f.statuses?.length?f.statuses:["draft","reschedule_pending"];let rows=data.containers.filter(c=>isContainerVisible(c)&&(f.warehouse==="all"||c.warehouse===f.warehouse)&&(f.customer==="all"||c.customer===f.customer)&&(!f.query||`${c.number} ${c.reference} ${c.customer}`.toLowerCase().includes(f.query.toLowerCase())));if(onlyAvailable)rows=rows.filter(c=>!bookingForContainer(c.id));else if(selected.length<Object.keys(statusMap).length)rows=rows.filter(c=>selected.includes(bookingForContainer(c.id)?.status||"draft"));$("#view").innerHTML=`<section class="panel"><div class="toolbar"><input class="input" placeholder="搜索柜号或参考号" value="${esc(f.query)}" oninput="App.setFilter('query',this.value)"><select class="select" onchange="App.setFilter('customer',this.value)">${options(data.customers.filter(x=>x.active).map(x=>({value:x.code,label:`${x.code} · ${x.name}`})),f.customer,"全部客户")}</select><select class="select" onchange="App.setFilter('warehouse',this.value)">${options(data.warehouses.filter(x=>x.active).map(x=>({value:x.id,label:x.name})),f.warehouse,"全部仓库")}</select>${onlyAvailable?"":statusFilterControl()}</div>${containerTable(rows)}</section>`}
  function renderBookingCenter(){renderContainers(true)}function setFilter(k,v){session.filters[k]=v;render()}
  function statusMenuToggled(open){session.statusMenuOpen=open}
  function toggleStatus(status,checked){const allKeys=Object.keys(statusMap),selected=new Set(session.filters.statuses||[]);if(status==="all"){session.filters.statuses=checked?[...allKeys]:["draft","reschedule_pending"]}else{checked?selected.add(status):selected.delete(status);session.filters.statuses=selected.size?[...selected]:["draft","reschedule_pending"]}session.statusMenuOpen=true;renderContainers(false)}
  function containerTable(rows){if(!rows.length)return '<div class="empty"><strong>没有符合条件的货柜</strong>调整筛选条件或新增货柜。</div>';return `<div class="table-wrap"><table class="data-table"><thead><tr><th>柜号</th><th>客户</th><th>仓库</th><th>尺寸</th><th>参考号</th><th>SKU / 件数</th><th>预约状态</th><th>操作</th></tr></thead><tbody>${rows.map(c=>{const b=bookingForContainer(c.id);return `<tr><td><a href="#" onclick="App.openDetail('${c.id}');return false">${esc(c.number)}</a></td><td>${esc(c.customer)}<span class="sub">${esc(customer(c.customer)?.name)}</span></td><td>${esc(warehouse(c.warehouse)?.name)}</td><td>${c.size} 尺</td><td>${esc(c.reference)}</td><td>${c.sku} / ${c.pieces}</td><td>${b?badge(b.status,b.super):badge("draft")}</td><td><div class="row-actions">${!b?`<button class="btn small primary" onclick="App.openBooking('${c.id}')">预约</button>`:""}${b?.status==="reschedule_pending"?`<button class="btn small primary" onclick="App.acceptReschedule('${b.id}')">接受</button><button class="btn small" onclick="App.rejectReschedule('${b.id}')">拒绝</button>`:""}${b?.status==="confirmed"?`<button class="btn small danger" onclick="App.cancelBooking('${b.id}')">取消</button>`:""}<button class="btn small" onclick="App.openDetail('${c.id}')">详情</button></div></td></tr>`}).join("")}</tbody></table></div>`}
  function dateInfo(date,wid){const ss=data.slots.filter(s=>s.warehouse===wid&&s.date===date&&s.active);if(!ss.length)return {state:"closed",label:"未开放"};const slotRem=ss.reduce((n,s)=>n+Math.max(0,remaining(s)),0),totalRem=Math.max(0,dailyCap(wid,date)-dailyCount(wid,date)),rem=Math.min(slotRem,totalRem);return rem>0?{state:"open",label:`可约 ${rem} 柜`}:{state:"full",label:"已满 · 可申请"}}
  function dateCard(date,wid,selected=false,click=""){const i=dateInfo(date,wid);return `<button class="date-card ${i.state} ${selected?"selected":""}" ${click?`onclick="${click}"`:""}><strong>${cnDate(date)}</strong><span>${i.label}</span></button>`}
  function slotPanel(wid,date){const ss=data.slots.filter(s=>s.warehouse===wid&&s.date===date);return `<aside class="panel"><div class="panel-head"><div><h2>当日 Slot</h2><p>${esc(warehouse(wid)?.name)} · ${cnDate(date)} · 总量 ${dailyCount(wid,date)}/${dailyCap(wid,date)}</p></div></div><div class="slot-list">${ss.length?ss.map(slotRow).join(""):'<div class="empty"><strong>尚未配置</strong>该日期没有开放 Slot。</div>'}</div></aside>`}
  function slotRow(s){const used=bookingCount(s.id),pct=s.capacity?Math.min(100,Math.round(used/s.capacity*100)):100,rem=remaining(s);return `<div class="slot-row"><div class="slot-top"><div><strong>${s.time}</strong><div class="slot-meta">${used} / ${s.capacity} 柜 · ${rem>0?`剩余 ${rem}`:rem===0?"已满":`超额 ${Math.abs(rem)}`}</div></div>${slotBadge(s)}</div><div class="progress"><i class="${rem<0?"over":rem===0?"hot":""}" style="width:${pct}%"></i></div></div>`}
  function bookingTable(rows,compact=false){rows=rows.filter(b=>isContainerVisible(container(b.containerId)));if(!rows.length)return '<div class="empty"><strong>暂无预约</strong>新的预约会显示在这里。</div>';return `<div class="table-wrap"><table class="data-table"><thead><tr><th>柜号</th><th>客户 / 仓库</th><th>尺寸</th><th>预约时间</th><th>状态</th>${compact?"":"<th>操作</th>"}</tr></thead><tbody>${rows.map(b=>{const c=container(b.containerId),s=slot(b.slotId);return `<tr><td><a href="#" onclick="App.openDetail('${c.id}');return false">${esc(c.number)}</a></td><td>${esc(c.customer)}<span class="sub">${esc(warehouse(c.warehouse)?.name)}</span></td><td>${c.size} 尺</td><td>${s?`${cnDate(s.date)} ${s.time}`:"待指定"}</td><td>${badge(b.status,b.super)}</td>${compact?"":`<td><button class="btn small" onclick="App.openDetail('${c.id}')">详情</button></td>`}</tr>`}).join("")}</tbody></table></div>`}

  function renderCustomers(){setHeader("客户管理","由客服维护客户主数据，已有业务记录的客户通过停用管理",`<button class="btn primary" onclick="App.openCustomer()">＋ 新增客户</button>`);$("#view").innerHTML=`<section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>客户代码</th><th>客户名称</th><th>联系人</th><th>电话</th><th>默认每日上限</th><th>状态</th><th>操作</th></tr></thead><tbody>${data.customers.map(c=>`<tr><td><b>${esc(c.code)}</b></td><td>${esc(c.name)}</td><td>${esc(c.contact||"—")}</td><td>${esc(c.phone||"—")}</td><td>${c.defaultDailyMax||"—"} 柜</td><td>${c.active?'<span class="badge ok">启用</span>':'<span class="badge neutral">停用</span>'}</td><td><div class="row-actions"><button class="btn small" onclick="App.openCustomer('${c.code}')">编辑</button><button class="btn small ${c.active?"danger":""}" onclick="App.toggleCustomer('${c.code}')">${c.active?"停用":"启用"}</button></div></td></tr>`).join("")}</tbody></table></div></section>`}
  function openCustomer(code=""){const c=customer(code)||{};const body=`<div class="form-grid"><div class="field"><label>客户代码 *</label><input id="master-code" class="input" value="${esc(c.code||"")}" ${code?"disabled":""} placeholder="例如 ALP-001"></div><div class="field"><label>客户名称 *</label><input id="master-name" class="input" value="${esc(c.name||"")}"></div><div class="field"><label>联系人</label><input id="master-contact" class="input" value="${esc(c.contact||"")}"></div><div class="field"><label>联系电话</label><input id="master-phone" class="input" value="${esc(c.phone||"")}"></div><div class="field"><label>默认单日最大预约量 *</label><input id="master-limit" class="input" type="number" min="1" value="${c.defaultDailyMax||6}"></div><div class="field wide"><label>备注</label><textarea id="master-note" class="textarea">${esc(c.note||"")}</textarea></div></div>`;openModal(code?"编辑客户":"新增客户",body,`<button class="btn" onclick="App.closeModal()">取消</button><button class="btn primary" onclick="App.saveCustomer('${esc(code)}')">保存</button>`)}
  function saveCustomer(oldCode=""){const code=val("#master-code").toUpperCase(),name=val("#master-name"),limit=Number(val("#master-limit"));if(!code)return fieldError("#master-code","请填写客户代码");if(!name)return fieldError("#master-name","请填写客户名称");if(limit<1)return fieldError("#master-limit","每日最大预约量至少为 1");if(!oldCode&&customer(code))return fieldError("#master-code","客户代码已存在");const target=customer(oldCode);const obj={code,name,contact:val("#master-contact"),phone:val("#master-phone"),defaultDailyMax:limit,note:val("#master-note"),active:target?.active??true};target?Object.assign(target,obj):data.customers.push(obj);log(oldCode?"编辑客户":"新增客户",code);save();closeModal();toast("客户资料已保存");render()}
  function toggleCustomer(code){const c=customer(code);c.active=!c.active;log(c.active?"启用客户":"停用客户",code);save();toast(c.active?"客户已启用":"客户已停用，历史数据保留");render()}
  function renderWarehouses(){setHeader("仓库管理","由客服维护仓库主数据，仓库可停用但不会删除历史记录",`<button class="btn primary" onclick="App.openWarehouse()">＋ 新增仓库</button>`);$("#view").innerHTML=`<section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>仓库代码</th><th>仓库名称</th><th>地址</th><th>联系人</th><th>默认日总量</th><th>状态</th><th>操作</th></tr></thead><tbody>${data.warehouses.map(w=>`<tr><td><b>${esc(w.id)}</b></td><td>${esc(w.name)}</td><td>${esc(w.address||"—")}</td><td>${esc(w.contact||"—")}<span class="sub">${esc(w.phone||"")}</span></td><td>${w.defaultDailyTotal||"—"} 柜</td><td>${w.active?'<span class="badge ok">启用</span>':'<span class="badge neutral">停用</span>'}</td><td><div class="row-actions"><button class="btn small" onclick="App.openWarehouse('${w.id}')">编辑</button><button class="btn small ${w.active?"danger":""}" onclick="App.toggleWarehouse('${w.id}')">${w.active?"停用":"启用"}</button></div></td></tr>`).join("")}</tbody></table></div></section>`}
  function openWarehouse(id=""){const w=warehouse(id)||{};const body=`<div class="form-grid"><div class="field"><label>仓库代码 *</label><input id="master-code" class="input" value="${esc(w.id||"")}" ${id?"disabled":""} placeholder="例如 WH04"></div><div class="field"><label>仓库名称 *</label><input id="master-name" class="input" value="${esc(w.name||"")}"></div><div class="field wide"><label>地址</label><input id="master-address" class="input" value="${esc(w.address||"")}"></div><div class="field"><label>联系人</label><input id="master-contact" class="input" value="${esc(w.contact||"")}"></div><div class="field"><label>联系电话</label><input id="master-phone" class="input" value="${esc(w.phone||"")}"></div><div class="field"><label>默认单日总预约量 *</label><input id="master-limit" class="input" type="number" min="1" value="${w.defaultDailyTotal||20}"></div><div class="field wide"><label>备注</label><textarea id="master-note" class="textarea">${esc(w.note||"")}</textarea></div></div>`;openModal(id?"编辑仓库":"新增仓库",body,`<button class="btn" onclick="App.closeModal()">取消</button><button class="btn primary" onclick="App.saveWarehouse('${esc(id)}')">保存</button>`)}
  function saveWarehouse(oldId=""){const id=val("#master-code").toUpperCase(),name=val("#master-name"),limit=Number(val("#master-limit"));if(!id)return fieldError("#master-code","请填写仓库代码");if(!name)return fieldError("#master-name","请填写仓库名称");if(limit<1)return fieldError("#master-limit","单日总预约量至少为 1");if(!oldId&&warehouse(id))return fieldError("#master-code","仓库代码已存在");const target=warehouse(oldId),obj={id,name,address:val("#master-address"),contact:val("#master-contact"),phone:val("#master-phone"),defaultDailyTotal:limit,note:val("#master-note"),active:target?.active??true};target?Object.assign(target,obj):data.warehouses.push(obj);log(oldId?"编辑仓库":"新增仓库",id);save();closeModal();toast("仓库资料已保存");render()}
  function toggleWarehouse(id){const w=warehouse(id);w.active=!w.active;log(w.active?"启用仓库":"停用仓库",id);save();toast(w.active?"仓库已启用":"仓库已停用，历史数据保留");render()}

  function renderOpsDashboard(){const overSlots=data.slots.filter(s=>bookingCount(s.id)>s.capacity).length;setHeader("运营看板","审核预约并掌握各仓库容量",`<button class="btn" onclick="App.go('slots')">配置 Slot</button><button class="btn primary" onclick="App.openSuperBooking()">⚡ 超级预约</button>`);$("#view").innerHTML=`<section class="stat-grid">${stat("待审核",pendingCount(),"需要运营处理","hot")}${stat("待客服确认",data.bookings.filter(b=>b.status==="reschedule_pending").length,"持续占用指定 Slot")}${stat("今日有效预约",activeBookings().filter(b=>slot(b.slotId)?.date===plusDays(0)).length,"全部仓库")}${stat("超额 Slot",overSlots,"超级预约或人工通过")}</section><section class="grid-2"><div class="panel"><div class="panel-head"><div><h2>待处理预约</h2><p>优先处理满额或触发日限额的申请</p></div><button class="btn small" onclick="App.go('audit')">全部审核</button></div>${auditTable(data.bookings.filter(b=>b.status==="pending").slice(0,5))}</div>${slotPanel("WH01",plusDays(0))}</section>`}
  function renderAudit(){setHeader("预约审核",`${pendingCount()} 条申请等待处理`,"");$("#view").innerHTML=`<section class="panel"><div class="toolbar"><span class="notice warn"><strong>审核规则</strong>通过可人工超额；指定新日期会临时占用 Slot，直到客服确认或拒绝。</span></div>${auditTable(data.bookings.filter(b=>b.status==="pending"))}</section>`}
  function auditTable(rows){rows=rows.filter(b=>isContainerVisible(container(b.containerId)));if(!rows.length)return '<div class="empty"><strong>没有待审核预约</strong>当前所有申请均已处理。</div>';return `<div class="table-wrap"><table class="data-table"><thead><tr><th>预约编号</th><th>柜号 / 尺寸</th><th>客户</th><th>申请仓库</th><th>申请 Slot</th><th>容量</th><th>操作</th></tr></thead><tbody>${rows.map(b=>{const c=container(b.containerId),s=slot(b.slotId);return `<tr><td>${esc(b.id)}</td><td><a href="#" onclick="App.openDetail('${c.id}');return false">${esc(c.number)}</a><span class="sub">${c.size} 尺</span></td><td>${esc(c.customer)}</td><td>${esc(warehouse(c.warehouse)?.name)}</td><td>${cnDate(s.date)} ${s.time}</td><td>${bookingCount(s.id)}/${s.capacity} · ${b.pendingReason||"已满"}</td><td><button class="btn small primary" onclick="App.openReview('${b.id}')">审核</button></td></tr>`}).join("")}</tbody></table></div>`}
  function renderSlots(){setHeader("Slot 配置","支持同时选择多个日期，统一配置时间点、日总量与客户日限额",`<button class="btn primary" onclick="App.openAddSlot()">＋ 批量配置 Slot</button>`);const wid=session.filters.warehouse==="all"?data.warehouses.find(x=>x.active)?.id:session.filters.warehouse,rows=data.slots.filter(s=>s.warehouse===wid&&s.date>=plusDays(0)).slice(0,40);$("#view").innerHTML=`<section class="panel"><div class="toolbar"><select class="select" onchange="App.setFilter('warehouse',this.value)">${options(data.warehouses.filter(x=>x.active).map(x=>({value:x.id,label:x.name})),wid)}</select><span class="notice"><strong>容量口径</strong>已预约、待客服确认、到场及完成均占用容量；超级预约不受限制但会显示超额。</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>日期</th><th>时间</th><th>时间点容量</th><th>当日总量</th><th>已占用</th><th>剩余 / 超额</th><th>状态</th><th>操作</th></tr></thead><tbody>${rows.map(s=>{const used=bookingCount(s.id),rem=remaining(s);return `<tr><td>${cnDateLong(s.date)}</td><td><b>${s.time}</b></td><td>${s.capacity}</td><td>${dailyCount(wid,s.date)} / ${dailyCap(wid,s.date)}</td><td>${used}</td><td>${rem>=0?`剩余 ${rem}`:`超额 ${Math.abs(rem)}`}</td><td>${slotBadge(s)}</td><td><button class="btn small" onclick="App.toggleSlot('${s.id}')">${s.active?"停用":"启用"}</button></td></tr>`}).join("")}</tbody></table></div></section>`}
  function renderSuperView(){setHeader("超级预约","不受 Slot 时间、日总量和客户限额约束，仅限授权运营或 IT",`<button class="btn primary" onclick="App.openSuperBooking()">⚡ 创建超级预约</button>`);$("#view").innerHTML=`<section class="panel"><div class="panel-body"><div class="notice warn"><strong>高权限操作</strong>超级预约直接进入仓库日历；每次必须选择货柜并填写原因，操作会记录日志。</div></div>${bookingTable(data.bookings.filter(b=>b.super))}</section>`}

  function renderWarehouseCalendar(){const wid=session.filters.warehouse;setHeader("仓库日历","日历仅显示每日预约数量，点击日期查看货柜详情",`<select class="select" onchange="App.setFilter('warehouse',this.value)">${options(data.warehouses.filter(x=>x.active).map(x=>({value:x.id,label:x.name})),wid,"全部仓库")}</select><button class="btn" onclick="App.exportMonth()">导出本月明细</button>`);const today=new Date(),y=today.getFullYear(),m=today.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),days=[];for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const date=iso(d),bs=warehouseBookings(date,wid),over=bs.some(b=>b.super);days.push(`<button class="calendar-day ${d.getMonth()!==m?"muted":""} ${date===iso(today)?"today":""} ${over?"over":""}" onclick="App.openDay('${date}')"><span class="num">${d.getDate()}</span>${bs.length?`<span class="metrics"><span class="booked">预约 ${bs.length} 柜</span></span>`:""}</button>`)}$("#view").innerHTML=`<section class="panel"><div class="panel-head"><div><h2>${y}年${m+1}月</h2><p>${wid==="all"?"全部仓库":warehouse(wid)?.name}</p></div><div class="legend"><span>预约</span><span>已完成</span><span>超级预约</span></div></div><div class="calendar-wrap"><div class="calendar-head"><span>日</span><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span></div><div class="calendar">${days.join("")}</div></div></section>`}
  function warehouseBookings(date,wid="all"){return data.bookings.filter(b=>["confirmed","arrived","completed"].includes(b.status)&&isContainerVisible(container(b.containerId))&&slot(b.slotId)?.date===date&&(wid==="all"||container(b.containerId)?.warehouse===wid))}
  function renderWarehouseTasks(){const wid=session.filters.warehouse;setHeader("仓库作业清单","登记到场与完成卸货；完成登记可填写备注",`<select class="select" onchange="App.setFilter('warehouse',this.value)">${options(data.warehouses.filter(x=>x.active).map(x=>({value:x.id,label:x.name})),wid,"全部仓库")}</select><button class="btn" onclick="App.exportTasks()">导出当前明细</button>`);const rows=data.bookings.filter(b=>["confirmed","arrived","completed"].includes(b.status)&&isContainerVisible(container(b.containerId))&&(wid==="all"||container(b.containerId)?.warehouse===wid));$("#view").innerHTML=`<section class="panel">${warehouseTaskTable(rows)}</section>`}
  function warehouseTaskTable(rows){if(!rows.length)return '<div class="empty"><strong>暂无仓库任务</strong>已通过的预约会显示在这里。</div>';return `<div class="table-wrap"><table class="data-table"><thead><tr><th>预约时间</th><th>柜号</th><th>仓库</th><th>客户</th><th>尺寸</th><th>登记时间</th><th>完成时间 / 备注</th><th>状态</th><th>操作</th></tr></thead><tbody>${rows.map(b=>{const c=container(b.containerId),s=slot(b.slotId);return `<tr><td>${cnDate(s.date)} ${s.time}</td><td><a href="#" onclick="App.openDetail('${c.id}');return false">${esc(c.number)}</a></td><td>${esc(warehouse(c.warehouse)?.name)}</td><td>${esc(c.customer)}</td><td>${c.size} 尺</td><td>${esc(b.arrivedAt||"—")}</td><td>${esc(b.completedAt||"—")}<span class="sub">${esc(b.completionNote||"")}</span></td><td>${badge(b.status,b.super)}</td><td><div class="row-actions">${b.status==="confirmed"?`<button class="btn small primary" onclick="App.markArrived('${b.id}')">登记到场</button>`:""}${b.status==="arrived"?`<button class="btn small primary" onclick="App.openComplete('${b.id}')">完成卸货</button>`:""}<button class="btn small" onclick="App.openDetail('${c.id}')">详情</button></div></td></tr>`}).join("")}</tbody></table></div>`}
  function exportRows(rows,name){const header=["预约时间","柜号","客户代码","客户名称","仓库","登记时间","卸货完成时间","卸货完成备注"],csv=[header,...rows.map(b=>{const c=container(b.containerId),s=slot(b.slotId);return [`${s?.date||""} ${s?.time||""}`,c?.number||"",c?.customer||"",customer(c?.customer)?.name||"",warehouse(c?.warehouse)?.name||"",b.arrivedAt||"",b.completedAt||"",b.completionNote||""]})].map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\r\n");const blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href);toast("明细已导出，可直接用 Excel 打开")}
  function exportMonth(){const today=new Date(),prefix=`${today.getFullYear()}-${pad(today.getMonth()+1)}`,wid=session.filters.warehouse,rows=data.bookings.filter(b=>{const s=slot(b.slotId),c=container(b.containerId);return ["confirmed","arrived","completed"].includes(b.status)&&isContainerVisible(c)&&s?.date.startsWith(prefix)&&(wid==="all"||c?.warehouse===wid)});exportRows(rows,`仓库预约明细-${prefix}.csv`)}
  function exportTasks(){const wid=session.filters.warehouse,rows=data.bookings.filter(b=>["confirmed","arrived","completed"].includes(b.status)&&isContainerVisible(container(b.containerId))&&(wid==="all"||container(b.containerId)?.warehouse===wid));exportRows(rows,"仓库作业明细.csv")}
  function openDay(date){const rows=warehouseBookings(date,session.filters.warehouse);openModal(`${cnDateLong(date)} · 预约货柜`,rows.length?warehouseTaskTable(rows):'<div class="empty"><strong>当天没有预约</strong>请切换日期查看。</div>',`<button class="btn" onclick="App.exportDay('${date}')">导出当日明细</button><button class="btn" onclick="App.closeModal()">关闭</button>`,true)}
  function exportDay(date){exportRows(warehouseBookings(date,session.filters.warehouse),`预约明细-${date}.csv`)}

  function renderITDashboard(){setHeader("系统总览","后台 IT 拥有全部业务权限及账号管理权限",`<button class="btn primary" onclick="App.go('accounts')">账号管理</button>`);$("#view").innerHTML=`<section class="stat-grid">${stat("启用账号",data.accounts.filter(a=>a.active).length,"全部岗位")}${stat("客户",data.customers.length,"含停用客户")}${stat("仓库",data.warehouses.length,"含停用仓库")}${stat("操作日志",data.logs.length,"最近 200 条")}</section><section class="panel"><div class="panel-head"><div><h2>最近系统操作</h2><p>登录、配置、审核与账号变更均会留痕</p></div></div>${logsTable(data.logs.slice(0,15))}</section>`}
  function logsTable(rows){if(!rows.length)return '<div class="empty"><strong>暂无日志</strong>新的系统操作会显示在这里。</div>';return `<div class="table-wrap"><table class="data-table"><thead><tr><th>时间</th><th>操作人</th><th>岗位</th><th>动作</th><th>详情</th></tr></thead><tbody>${rows.map(l=>`<tr><td>${esc(l.time)}</td><td>${esc(l.user||"—")}</td><td>${esc(roles[l.role]?.label||l.role||"—")}</td><td><b>${esc(l.action)}</b></td><td>${esc(l.detail)}</td></tr>`).join("")}</tbody></table></div>`}
  function renderAccounts(){setHeader("账号管理","云端共享账号：创建后可在其他设备登录",`<button class="btn primary" onclick="App.openAccount()">＋ 新增账号</button>`);$("#view").innerHTML=`<section class="panel"><div class="panel-body"><div class="notice warn"><strong>全设备生效</strong>新增、修改密码、岗位调整与停用会同步到所有设备。不能停用当前登录账号，且必须至少保留一个启用的后台 IT 账号。</div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>账号</th><th>姓名</th><th>岗位</th><th>状态</th><th>最近登录</th><th>操作</th></tr></thead><tbody>${data.accounts.map(a=>`<tr><td><b>${esc(a.account)}</b></td><td>${esc(a.name)}</td><td>${esc(roles[a.role]?.label)}</td><td>${a.active?'<span class="badge ok">启用</span>':'<span class="badge neutral">停用</span>'}</td><td>${esc(a.lastLogin||"—")}</td><td><div class="row-actions"><button class="btn small" onclick="App.openAccount('${a.id}')">编辑 / 重置密码</button><button class="btn small ${a.active?"danger":""}" onclick="App.toggleAccount('${a.id}')">${a.active?"停用":"启用"}</button></div></td></tr>`).join("")}</tbody></table></div></section><section class="panel" style="margin-top:18px"><div class="panel-head"><h2>账号操作日志</h2></div>${logsTable(data.logs.filter(l=>/账号|登录|密码/.test(l.action)).slice(0,20))}</section>`}
  function openAccount(id=""){const a=data.accounts.find(x=>x.id===id)||{};const body=`<div class="form-grid"><div class="field"><label>登录账号 *</label><input id="account-name" class="input" value="${esc(a.account||"")}" ${id?"disabled":""}></div><div class="field"><label>姓名 *</label><input id="account-user" class="input" value="${esc(a.name||"")}"></div><div class="field"><label>岗位 *</label><select id="account-role" class="select">${options(Object.entries(roles).map(([value,r])=>({value,label:r.label})),a.role||"service")}</select></div><div class="field"><label>${id?"新密码（留空则不修改）":"初始密码 *"}</label><input id="account-password" class="input" type="text" placeholder="至少 6 位"></div></div>`;openModal(id?"编辑账号":"新增账号",body,`<button class="btn" onclick="App.closeModal()">取消</button><button class="btn primary" onclick="App.saveAccount('${id}')">保存账号</button>`)}
  async function saveAccount(id=""){const account=val("#account-name"),name=val("#account-user"),role=val("#account-role"),password=val("#account-password");if(!account)return fieldError("#account-name","请填写登录账号");if(!/^[A-Za-z0-9._-]{3,50}$/.test(account))return fieldError("#account-name","账号限 3 至 50 位英文、数字、点、下划线或短横线");if(!name)return fieldError("#account-user","请填写姓名");if(!id&&data.accounts.some(a=>a.account.toLowerCase()===account.toLowerCase()))return fieldError("#account-name","登录账号已存在");if(!id&&password.length<6)return fieldError("#account-password","初始密码至少 6 位");if(id&&password&&password.length<6)return fieldError("#account-password","新密码至少 6 位");try{await api(id?`/api/accounts/${encodeURIComponent(id)}`:"/api/accounts",{method:id?"PATCH":"POST",body:JSON.stringify({account,name,role,...(password?{password}:{})})});await refreshAccounts();log(id?(password?"编辑账号并重置密码":"编辑账号"):"新增账号",account);closeModal();toast("账号已保存，其他设备现在可以使用");render()}catch(error){toast(error.message)}}
  async function toggleAccount(id){const a=data.accounts.find(x=>x.id===id),targetActive=!a.active;if(a.id===session.user.id&&a.active){toast("不能停用当前登录账号");return}if(a.role==="it"&&a.active&&data.accounts.filter(x=>x.role==="it"&&x.active).length<=1){toast("系统必须至少保留一个启用的后台 IT 账号");return}try{await api(`/api/accounts/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify({active:targetActive})});await refreshAccounts();log(targetActive?"启用账号":"停用账号",a.account);toast(targetActive?"账号已启用":"账号已停用");render()}catch(error){toast(error.message)}}

  function openAddContainer(){const body=`<div class="form-grid"><div class="field"><label>客户代码 *</label><select id="c-customer" class="select">${options(data.customers.filter(x=>x.active).map(x=>({value:x.code,label:`${x.code} · ${x.name}`})))}</select></div><div class="field"><label>仓库 *</label><select id="c-warehouse" class="select">${options(data.warehouses.filter(x=>x.active).map(x=>({value:x.id,label:x.name})))}</select></div><div class="field"><label>柜号 *</label><input id="c-number" class="input" placeholder="例如 MSCU-728194"></div><div class="field"><label>货柜尺寸 *</label><select id="c-size" class="select"><option value="20">20 尺</option><option value="40">40 尺</option><option value="45">45 尺</option></select></div><div class="field wide"><label>参考号 *</label><input id="c-ref" class="input" placeholder="客户参考号"></div><div class="field"><label>SKU 数量 *</label><input id="c-sku" class="input" type="number" min="1"></div><div class="field"><label>件数 *</label><input id="c-pieces" class="input" type="number" min="1"></div></div>`;openModal("新增货柜",body,`<button class="btn" onclick="App.closeModal()">取消</button><button class="btn primary" onclick="App.addContainer()">保存货柜</button>`)}
  const normalizeContainerNumber=value=>String(value||"").trim().toUpperCase();
  const containerNumberExists=number=>data.containers.some(c=>normalizeContainerNumber(c.number)===normalizeContainerNumber(number));
  function addContainer(){const number=normalizeContainerNumber(val("#c-number")),reference=val("#c-ref"),sku=Number(val("#c-sku")),pieces=Number(val("#c-pieces")),customerCode=val("#c-customer"),warehouseCode=val("#c-warehouse");if(!customerCode||!customer(customerCode)?.active)return fieldError("#c-customer","请先选择启用的客户");if(!warehouseCode||!warehouse(warehouseCode)?.active)return fieldError("#c-warehouse","请先选择启用的仓库");if(!number)return fieldError("#c-number","请填写柜号");if(containerNumberExists(number))return fieldError("#c-number",`柜号 ${number} 已存在，不能重复创建`);if(!reference)return fieldError("#c-ref","请填写参考号");if(sku<1)return fieldError("#c-sku","SKU 数量至少为 1");if(pieces<1)return fieldError("#c-pieces","件数至少为 1");data.containers.push({id:uid("C"),number,size:val("#c-size"),reference,sku,pieces,customer:customerCode,warehouse:warehouseCode});log("新增货柜",number);save();closeModal();toast("货柜已保存");render()}
  function openBooking(containerId){const c=container(containerId);if(bookingForContainer(containerId)){toast("该货柜已有有效预约");return}session.bookingDraft={containerId,date:plusDays(1),slotId:null};renderBookingModal()}
  function renderBookingModal(){const d=session.bookingDraft,c=container(d.containerId),dates=[0,1,2,3,4,5,6].map(n=>{const date=plusDays(n);return dateCard(date,c.warehouse,d.date===date,`App.chooseBookingDate('${date}')`)}).join(""),ss=data.slots.filter(s=>s.warehouse===c.warehouse&&s.date===d.date&&s.active);const body=`<div class="notice"><strong>${esc(c.number)}</strong>${esc(customer(c.customer)?.name)} · ${c.size} 尺 · ${esc(warehouse(c.warehouse)?.name)}</div><h3 class="section-title" style="margin-top:20px">1. 选择预约日期</h3><div class="date-strip" style="padding:0 0 16px">${dates}</div><h3 class="section-title">2. 选择 Slot</h3><div class="slot-list" style="padding:0">${ss.length?ss.map(s=>{const decision=capacityDecision(c,s);return `<button class="slot-row ${d.slotId===s.id?"selected":""}" onclick="App.chooseBookingSlot('${s.id}')" style="text-align:left;${d.slotId===s.id?"box-shadow:0 0 0 2px var(--blue)":""}"><div class="slot-top"><strong>${s.time}</strong>${decision.ok?'<span class="badge ok">可预约</span>':'<span class="badge wait">已满 / 需审核</span>'}</div><div class="slot-meta">${bookingCount(s.id)} / ${s.capacity} 柜 · ${decision.reason}</div></button>`}).join(""):'<div class="empty"><strong>当日未开放</strong>请选择其他日期。</div>'}</div>`;openModal("为货柜发起预约",body,`<button class="btn" onclick="App.closeModal()">取消</button><button class="btn primary" ${d.slotId?"":"disabled"} onclick="App.submitBooking()">提交预约</button>`,true)}
  function chooseBookingDate(date){session.bookingDraft.date=date;session.bookingDraft.slotId=null;renderBookingModal()}function chooseBookingSlot(id){session.bookingDraft.slotId=id;renderBookingModal()}
  function submitBooking(){const d=session.bookingDraft,s=slot(d.slotId),c=container(d.containerId);if(!s)return;const decision=capacityDecision(c,s),b={id:`BK-${Date.now().toString().slice(-8)}`,containerId:d.containerId,slotId:s.id,status:decision.ok?"confirmed":"pending",pendingReason:decision.ok?"":decision.reason,super:false,createdBy:session.user.name,createdAt:nowText(),history:[{title:decision.ok?"预约自动通过":"提交预约审核",time:nowText(),note:decision.reason}]};data.bookings.push(b);log("提交预约",`${b.id} · ${decision.reason}`);save();closeModal();toast(decision.ok?"预约已自动通过":`${decision.reason}，已提交运营审核`);render()}

  function openReview(id){const b=data.bookings.find(x=>x.id===id),c=container(b.containerId),s=slot(b.slotId);const body=`<div class="detail-grid"><div class="detail"><span>柜号</span><strong>${esc(c.number)} · ${c.size} 尺</strong></div><div class="detail"><span>客户</span><strong>${esc(c.customer)}</strong></div><div class="detail"><span>申请仓库</span><strong>${esc(warehouse(c.warehouse)?.name)}</strong></div><div class="detail"><span>申请 Slot</span><strong>${cnDate(s.date)} ${s.time}</strong></div><div class="detail"><span>当前容量</span><strong>${bookingCount(s.id)} / ${s.capacity}</strong></div><div class="detail"><span>触发规则</span><strong>${esc(b.pendingReason||"Slot 已满")}</strong></div></div><div class="field" style="margin-top:18px"><label>审核意见（拒绝时必填）</label><textarea id="review-note" class="textarea" placeholder="填写处理说明"></textarea></div>`;openModal("审核预约",body,`<button class="btn danger" onclick="App.rejectBooking('${id}')">拒绝</button><button class="btn" onclick="App.openReschedule('${id}')">指定新日期</button><button class="btn primary" onclick="App.approveBooking('${id}')">通过</button>`)}
  function approveBooking(id){const b=data.bookings.find(x=>x.id===id);b.status="confirmed";b.reviewNote=val("#review-note")||"运营人工通过";b.history.unshift({title:"运营审核通过",time:nowText(),note:b.reviewNote});log("审核通过",id);save();closeModal();toast("预约已通过");renderShell();render()}
  function rejectBooking(id){const note=val("#review-note");if(!note)return fieldError("#review-note","请填写拒绝原因");const b=data.bookings.find(x=>x.id===id);b.status="rejected";b.reviewNote=note;b.history.unshift({title:"运营拒绝预约",time:nowText(),note});log("拒绝预约",id);save();closeModal();toast("预约已拒绝，可重新预约");renderShell();render()}
  function openReschedule(id){const b=data.bookings.find(x=>x.id===id),c=container(b.containerId),ss=data.slots.filter(s=>s.warehouse===c.warehouse&&s.active&&s.date>=plusDays(0));const body=`<div class="notice warn"><strong>临时占用</strong>指定后将保留该 Slot，直到客服接受或拒绝。</div><div class="form-grid" style="margin-top:18px"><div class="field wide"><label>新日期与 Slot *</label><select id="new-slot" class="select">${ss.map(s=>`<option value="${s.id}">${cnDateLong(s.date)} ${s.time} · ${remaining(s)>0?`剩余 ${remaining(s)}`:"已满"}</option>`).join("")}</select></div><div class="field wide"><label>调整原因 *</label><textarea id="new-note" class="textarea" placeholder="例如：原时段已满，建议调整至新时段"></textarea></div></div>`;openModal("指定新日期",body,`<button class="btn" onclick="App.closeModal()">取消</button><button class="btn primary" onclick="App.submitReschedule('${id}')">发送客服确认</button>`)}
  function submitReschedule(id){const note=val("#new-note");if(!note)return fieldError("#new-note","请填写调整原因");const b=data.bookings.find(x=>x.id===id);b.originalSlotId=b.originalSlotId||b.slotId;b.slotId=val("#new-slot");b.status="reschedule_pending";b.reviewNote=note;b.history.unshift({title:"运营指定新日期",time:nowText(),note});log("指定新日期",id);save();closeModal();toast("已发送客服确认并临时占用 Slot");renderShell();render()}
  function acceptReschedule(id){const b=data.bookings.find(x=>x.id===id);b.status="confirmed";b.history.unshift({title:"客服接受新日期",time:nowText(),note:"临时占用转为正式预约"});log("接受改期",id);save();toast("已接受新日期");render()}
  function rejectReschedule(id){if(!confirm("拒绝后将释放当前 Slot，本次预约结束，需要重新预约。确认拒绝吗？"))return;const b=data.bookings.find(x=>x.id===id);b.status="customer_rejected";b.history.unshift({title:"客服拒绝新日期",time:nowText(),note:"已释放临时占用，需重新预约"});log("拒绝改期",id);save();toast("已拒绝新日期，可重新预约");render()}
  function cancelBooking(id){if(!confirm("取消后会释放 Slot，若要更换日期需重新预约。确认取消吗？"))return;const b=data.bookings.find(x=>x.id===id);b.status="cancelled";b.history.unshift({title:"客服取消预约",time:nowText(),note:"Slot 已释放"});log("取消预约",id);save();toast("预约已取消");render()}

  function openAddSlot(){const wh=data.warehouses.find(x=>x.active);if(!wh){toast("请先创建并启用仓库");go("warehouses");return}const initial=plusDays(1);session.slotRows=[{time:"08:00",capacity:5},{time:"10:00",capacity:5}];session.slotMeta={wh:wh.id,dates:[initial],calendarMonth:initial.slice(0,7),total:20,cust:"",custMax:""};renderSlotModal()}
  function slotCalendarHtml(){const m=session.slotMeta,parts=m.calendarMonth.split("-").map(Number),year=parts[0],month=parts[1],first=new Date(year,month-1,1,12),offset=(first.getDay()+6)%7,start=new Date(year,month-1,1-offset,12),today=plusDays(0),cells=[];for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const date=iso(d),outside=d.getMonth()!==month-1,selected=m.dates.includes(date),past=date<today;cells.push(`<button type="button" class="slot-calendar-day ${outside?"outside":""} ${selected?"selected":""}" ${past?"disabled":""} onclick="App.toggleSlotDate('${date}')" aria-pressed="${selected}">${d.getDate()}</button>`)}return `<div class="slot-calendar-head"><button type="button" onclick="App.changeSlotMonth(-1)" aria-label="上个月">‹</button><strong>${year}年${month}月</strong><button type="button" onclick="App.changeSlotMonth(1)" aria-label="下个月">›</button></div><div class="slot-calendar-week"><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span><span>日</span></div><div class="slot-calendar-grid">${cells.join("")}</div>`}
  function renderSlotModal(){const m=session.slotMeta||{},dateChips=(m.dates||[]).map((d,i)=>`<span class="date-chip">${cnDateLong(d)}<button type="button" onclick="App.removeSlotDate(${i})" aria-label="移除 ${d}">×</button></span>`).join(""),rows=session.slotRows.map((r,i)=>`<div class="batch-slot-row"><div class="field"><label>时间点 ${i+1}</label><input class="input slot-time" type="time" value="${r.time}" onchange="App.updateSlotRow(${i},'time',this.value)"></div><div class="field"><label>可预约柜数</label><input class="input slot-cap" type="number" min="1" value="${r.capacity}" onchange="App.updateSlotRow(${i},'capacity',this.value)"></div><button class="icon-btn remove-row" onclick="App.removeSlotRow(${i})" aria-label="删除">×</button></div>`).join("");const body=`<div class="form-grid"><div class="field"><label>仓库 *</label><select id="slot-wh" class="select">${options(data.warehouses.filter(x=>x.active).map(x=>({value:x.id,label:x.name})),m.wh)}</select></div><div class="field wide"><label>日期（可多选）*</label><div id="slot-calendar" class="multi-date-picker"><div class="selected-count">已选择 <strong>${m.dates.length}</strong> 个日期</div>${slotCalendarHtml()}</div><div class="date-chips">${dateChips||'<span class="muted-text">请直接在日历中选择日期</span>'}</div><small>点击日期选中或取消；切换月份可跨月选择。</small></div><div class="field"><label>每日总预约量 *</label><input id="slot-total" class="input" type="number" min="1" value="${m.total||20}"></div><div class="field"><label>指定客户（可选）</label><select id="slot-customer" class="select"><option value="" ${m.cust?"":"selected"}>不单独配置</option>${options(data.customers.filter(x=>x.active).map(x=>({value:x.code,label:`${x.code} · ${x.name}`})),m.cust)}</select></div><div class="field"><label>该客户每日上限（可选）</label><input id="slot-customer-max" class="input" type="number" min="1" value="${esc(m.custMax||"")}" placeholder="选择客户后填写"></div></div><div class="batch-head"><h3 class="section-title">时间点与容量</h3><button class="btn small" onclick="App.addSlotRow()">＋ 添加时间点</button></div><div id="slot-rows" class="batch-list">${rows}</div>`;openModal("批量配置 Slot",body,`<button class="btn" onclick="App.closeModal()">取消</button><button class="btn primary" onclick="App.addSlots()">保存多日配置</button>`,true)}
  function captureSlotMeta(){if(!$("#slot-wh"))return;session.slotMeta={wh:val("#slot-wh"),dates:session.slotMeta?.dates||[],calendarMonth:session.slotMeta?.calendarMonth||plusDays(1).slice(0,7),total:Number(val("#slot-total")),cust:val("#slot-customer"),custMax:val("#slot-customer-max")};$$('.slot-time').forEach((e,i)=>session.slotRows[i].time=e.value);$$('.slot-cap').forEach((e,i)=>session.slotRows[i].capacity=Number(e.value))}
  function toggleSlotDate(date){captureSlotMeta();const dates=session.slotMeta.dates,index=dates.indexOf(date);index>=0?dates.splice(index,1):dates.push(date);dates.sort();renderSlotModal()}
  function changeSlotMonth(delta){captureSlotMeta();const [y,m]=session.slotMeta.calendarMonth.split("-").map(Number),d=new Date(y,m-1+delta,1,12);session.slotMeta.calendarMonth=`${d.getFullYear()}-${pad(d.getMonth()+1)}`;renderSlotModal()}
  function removeSlotDate(i){captureSlotMeta();session.slotMeta.dates.splice(i,1);renderSlotModal()}
  function updateSlotRow(i,key,value){session.slotRows[i][key]=key==="capacity"?Number(value):value}function addSlotRow(){captureSlotMeta();session.slotRows.push({time:"14:00",capacity:5});renderSlotModal()}function removeSlotRow(i){if(session.slotRows.length===1){toast("至少保留一个时间点");return}captureSlotMeta();session.slotRows.splice(i,1);renderSlotModal()}
  function addSlots(){captureSlotMeta();const {wh,dates,total,cust}=session.slotMeta,custMax=Number(session.slotMeta.custMax),rows=session.slotRows.map(r=>({time:r.time,capacity:Number(r.capacity)}));if(!dates.length)return fieldError("#slot-calendar","请至少在日历中选择一个日期");if(total<1)return fieldError("#slot-total","每日总预约量至少为 1");if(cust&&custMax<1)return fieldError("#slot-customer-max","选择客户后必须填写每日上限");if(rows.some(r=>!r.time||r.capacity<1)){toast("请完整填写每个时间点及容量");return}if(new Set(rows.map(r=>r.time)).size!==rows.length){toast("批量配置中不能有重复时间点");return}const conflicts=[];dates.forEach(date=>rows.forEach(r=>{if(data.slots.some(s=>s.warehouse===wh&&s.date===date&&s.time===r.time))conflicts.push(`${date} ${r.time}`)}));if(conflicts.length)return fieldError("#slot-calendar",`存在重复 Slot：${conflicts.slice(0,4).join("、")}${conflicts.length>4?" 等":""}`);const sum=rows.reduce((n,r)=>n+r.capacity,0);if(sum>total)return fieldError("#slot-total",`时间点容量合计 ${sum}，不能超过每日总预约量 ${total}`);dates.forEach(date=>{rows.forEach(r=>data.slots.push({id:uid("S"),warehouse:wh,date,time:r.time,capacity:r.capacity,active:true}));data.dailyCaps[dailyKey(wh,date)]=total;if(cust)data.dailyLimits[limitKey(wh,date,cust)]=custMax});log("多日批量配置 Slot",`${wh} · ${dates.length} 天 · 每天 ${rows.length} 个时间点 · 日总量 ${total}${cust?` · ${cust} 上限 ${custMax}`:""}`);save();closeModal();toast(`已为 ${dates.length} 个日期保存 ${dates.length*rows.length} 个 Slot`);render()}
  function toggleSlot(id){const s=slot(id);s.active=!s.active;log(s.active?"启用 Slot":"停用 Slot",id);save();toast(s.active?"Slot 已启用":"Slot 已停用");render()}

  function openSuperBooking(){session.superSelected=null;const body=`<div class="notice warn"><strong>超级权限</strong>可在任何日期和时间直接预约，不受 Slot、日总量与客户限额约束。</div><div class="form-grid" style="margin-top:18px"><div class="field wide search-wrap"><label>选择或检索货柜 *</label><div class="combo-input"><input id="super-search" class="input" placeholder="点击选择，或输入客户代码、客户名称、柜号、参考号" onfocus="App.openSuperList()" oninput="App.searchSuper(this.value)" autocomplete="off" role="combobox" aria-controls="super-results" aria-expanded="false"><button type="button" class="combo-toggle" onclick="App.toggleSuperList(event)" aria-label="展开货柜列表">⌄</button></div><input id="super-container" type="hidden"><div id="super-results" class="search-results" role="listbox"></div><div id="super-selected" class="selected-item is-hidden"></div></div><div class="field"><label>预约日期 *</label><input id="super-date" class="input" type="date" value="${plusDays(0)}"></div><div class="field"><label>预约时间 *</label><input id="super-time" class="input" type="time" value="18:00"></div><div class="field wide"><label>超级预约原因 *</label><textarea id="super-reason" class="textarea" placeholder="必须填写高权限操作原因"></textarea></div></div>`;openModal("创建超级预约",body,`<button class="btn" onclick="App.closeModal()">取消</button><button class="btn primary" onclick="App.createSuperBooking()">确认预约</button>`,true)}
  function openSuperList(){searchSuper($("#super-search")?.value||"")}
  function toggleSuperList(event){event?.stopPropagation();const box=$("#super-results");if(box?.classList.contains("open")){box.classList.remove("open");$("#super-search")?.setAttribute("aria-expanded","false")}else openSuperList()}
  function searchSuper(q){const box=$("#super-results");if(!box)return;const term=q.trim().toLowerCase(),available=data.containers.filter(c=>isContainerVisible(c)&&!bookingForContainer(c.id)&&(!term||`${c.customer} ${customer(c.customer)?.name} ${c.number} ${c.reference}`.toLowerCase().includes(term))).slice(0,10);box.innerHTML=available.length?available.map(c=>`<button type="button" role="option" onclick="App.selectSuper('${c.id}')"><strong>${esc(c.number)} · ${c.size} 尺</strong><span>${esc(c.customer)} · ${esc(customer(c.customer)?.name)} · ${esc(warehouse(c.warehouse)?.name)} · ${esc(c.reference)}</span></button>`).join(""):'<div class="search-empty">没有匹配的可预约货柜</div>';box.classList.add("open");$("#super-search")?.setAttribute("aria-expanded","true")}
  function selectSuper(id){const c=container(id);session.superSelected=id;$("#super-container").value=id;$("#super-search").value=`${c.number} · ${c.customer}`;$("#super-results").classList.remove("open");$("#super-search").setAttribute("aria-expanded","false");const picked=$("#super-selected");picked.innerHTML=`已选择 <strong>${esc(c.number)}</strong> · ${c.size} 尺 · ${esc(warehouse(c.warehouse)?.name)} <button onclick="App.clearSuper()">清除</button>`;picked.classList.remove("is-hidden");clearError("#super-search")}
  function clearSuper(){session.superSelected=null;$("#super-container").value="";$("#super-search").value="";$("#super-selected").classList.add("is-hidden");$("#super-results").classList.remove("open");$("#super-search").setAttribute("aria-expanded","false")}
  function createSuperBooking(){const containerId=val("#super-container"),reason=val("#super-reason"),date=val("#super-date"),time=val("#super-time");if(!containerId)return fieldError("#super-search","请先检索并选择一个货柜");if(!date)return fieldError("#super-date","请选择预约日期");if(!time)return fieldError("#super-time","请选择预约时间");if(!reason)return fieldError("#super-reason","请填写超级预约原因");const c=container(containerId);let s=data.slots.find(x=>x.warehouse===c.warehouse&&x.date===date&&x.time===time);if(!s){s={id:uid("S-SUPER"),warehouse:c.warehouse,date,time,capacity:0,active:true,superOnly:true};data.slots.push(s)}const b={id:`BK-S-${Date.now().toString().slice(-7)}`,containerId,slotId:s.id,status:"confirmed",super:true,createdBy:session.user.name,createdAt:nowText(),reviewNote:reason,history:[{title:"创建超级预约",time:nowText(),note:reason}]};data.bookings.push(b);log("超级预约",`${b.id} · ${reason}`);save();closeModal();toast("超级预约已创建并同步仓库日历");render()}

  function markArrived(id){const b=data.bookings.find(x=>x.id===id);b.status="arrived";b.arrivedAt=nowText();b.arrivedBy=session.user.name;b.history.unshift({title:"货柜已到场",time:b.arrivedAt,note:`由 ${session.user.name} 登记`});log("登记到场",id);save();toast("已记录到场时间");render()}
  function openComplete(id){const b=data.bookings.find(x=>x.id===id),c=container(b.containerId),s=slot(b.slotId);if(b.status!=="arrived"){toast("只有已到场货柜才能完成卸货");return}const body=`<div class="detail-grid"><div class="detail"><span>柜号</span><strong>${esc(c.number)}</strong></div><div class="detail"><span>客户</span><strong>${esc(c.customer)} · ${esc(customer(c.customer)?.name)}</strong></div><div class="detail"><span>预约时间</span><strong>${s.date} ${s.time}</strong></div><div class="detail"><span>到场登记</span><strong>${esc(b.arrivedAt||"—")}</strong></div></div><div class="field" style="margin-top:18px"><label>卸货完成备注（可选）</label><textarea id="complete-note" class="textarea" placeholder="例如：外包装完好、发现破损 2 件等"></textarea></div>`;openModal("完成卸货登记",body,`<button class="btn" onclick="App.closeModal()">取消</button><button class="btn primary" onclick="App.markCompleted('${id}')">确认完成</button>`)}
  function markCompleted(id){const b=data.bookings.find(x=>x.id===id);if(b.status!=="arrived"){toast("只有已到场货柜才能完成卸货");return}b.status="completed";b.completedAt=nowText();b.completedBy=session.user.name;b.completionNote=val("#complete-note");b.history.unshift({title:"完成卸货",time:b.completedAt,note:`由 ${session.user.name} 登记${b.completionNote?`：${b.completionNote}`:""}`});log("完成卸货",`${id}${b.completionNote?` · ${b.completionNote}`:""}`);save();closeModal();toast("卸货完成时间和备注已记录");render()}
  function openDetail(containerId){const c=container(containerId),b=[...data.bookings].reverse().find(x=>x.containerId===containerId),s=b?slot(b.slotId):null,el=$("#drawer");el.innerHTML=`<aside class="drawer" role="dialog" aria-modal="true"><header class="drawer-head"><div><h2>${esc(c.number)}</h2><span>${c.size} 尺 · ${esc(customer(c.customer)?.name)}</span></div><button class="close" onclick="App.closeDrawer()">×</button></header><div class="drawer-body"><div class="detail-grid"><div class="detail"><span>仓库</span><strong>${esc(warehouse(c.warehouse)?.name)}</strong></div><div class="detail"><span>客户代码</span><strong>${esc(c.customer)}</strong></div><div class="detail"><span>参考号</span><strong>${esc(c.reference)}</strong></div><div class="detail"><span>SKU / 件数</span><strong>${c.sku} / ${c.pieces}</strong></div><div class="detail"><span>预约状态</span><strong>${b?statusMap[b.status]?.[0]:"待预约"}</strong></div><div class="detail"><span>最终预约时间</span><strong>${s?`${cnDateLong(s.date)} ${s.time}`:"—"}</strong></div><div class="detail"><span>登记到场</span><strong>${esc(b?.arrivedAt||"—")}</strong></div><div class="detail"><span>完成卸货</span><strong>${esc(b?.completedAt||"—")}</strong></div><div class="detail"><span>完成登记人</span><strong>${esc(b?.completedBy||"—")}</strong></div><div class="detail"><span>卸货完成备注</span><strong>${esc(b?.completionNote||"—")}</strong></div></div>${b?.reviewNote?`<div class="notice warn" style="margin-top:16px"><strong>处理意见</strong>${esc(b.reviewNote)}</div>`:""}<section class="history"><h3 class="section-title">处理记录</h3>${b?.history?.length?b.history.map(h=>`<div class="history-item"><b>${esc(h.title)}</b><p>${esc(h.time)} · ${esc(h.note)}</p></div>`).join(""):'<div class="empty">暂无处理记录</div>'}</section></div></aside>`;el.classList.remove("is-hidden")}
  function downloadTemplate(){const csv="仓库代码,柜号,货柜尺寸,参考号,SKU数量,件数,客户代码\nWH01,MSCU-123456,40,REF-001,20,500,ALP-001\n",blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="货柜批量导入模板.csv";a.click();URL.revokeObjectURL(a.href);toast("模板已下载，可用 Excel 打开填写")}
  function openImport(){const body=`<div class="notice"><strong>Excel 导入</strong>使用 Excel 可直接编辑的 CSV 模板。必填：仓库代码、柜号、货柜尺寸、参考号、SKU数量、件数、客户代码。</div><div class="form-grid" style="margin-top:18px"><div class="field wide"><label>上传填写后的 CSV *</label><input id="import-file" class="input" type="file" accept=".csv,text/csv"></div></div>`;openModal("批量导入货柜",body,`<button class="btn" onclick="App.downloadTemplate()">下载模板</button><button class="btn primary" onclick="App.importCsv()">开始导入</button>`)}
  function importCsv(){const file=$("#import-file")?.files[0];if(!file)return fieldError("#import-file","请先选择 CSV 文件");const reader=new FileReader();reader.onload=()=>{const lines=String(reader.result).replace(/^\uFEFF/,"").split(/\r?\n/).filter(line=>line.trim());if(lines.length<2){toast("文件中没有可导入数据");return}const rows=[],errors=[],existingNumbers=new Set(data.containers.map(c=>normalizeContainerNumber(c.number))),fileNumbers=new Map();lines.slice(1).forEach((line,index)=>{const rowNumber=index+2,columns=line.split(",").map(x=>x.trim());if(columns.length!==7){errors.push(`第 ${rowNumber} 行：列数不正确，应为 7 列`);return}const [wh,rawNumber,size,reference,sku,pieces,cust]=columns,number=normalizeContainerNumber(rawNumber),rowErrors=[];if(!number)rowErrors.push("柜号不能为空");else if(existingNumbers.has(number))rowErrors.push(`柜号 ${number} 已存在于系统`);else if(fileNumbers.has(number))rowErrors.push(`柜号 ${number} 与第 ${fileNumbers.get(number)} 行重复`);else fileNumbers.set(number,rowNumber);const whRecord=warehouse(wh);if(!whRecord)rowErrors.push(`仓库代码 ${wh||"（空）"} 不存在`);else if(!whRecord.active)rowErrors.push(`仓库代码 ${wh} 已停用`);const customerRecord=customer(cust);if(!customerRecord)rowErrors.push(`客户代码 ${cust||"（空）"} 不存在`);else if(!customerRecord.active)rowErrors.push(`客户代码 ${cust} 已停用`);if(!["20","40","45"].includes(size))rowErrors.push("货柜尺寸只能是 20、40 或 45");if(!reference)rowErrors.push("参考号不能为空");if(!Number.isInteger(Number(sku))||Number(sku)<1)rowErrors.push("SKU 数量必须是大于 0 的整数");if(!Number.isInteger(Number(pieces))||Number(pieces)<1)rowErrors.push("件数必须是大于 0 的整数");if(rowErrors.length)errors.push(`第 ${rowNumber} 行：${rowErrors.join("；")}`);else rows.push({id:uid("C"),number,size,reference,sku:Number(sku),pieces:Number(pieces),customer:cust,warehouse:wh})});if(errors.length){log("批量导入失败",`${errors.length} 行数据有误，未写入任何货柜`);save();const body=`<div class="notice warn"><strong>本次导入已取消</strong>发现 ${errors.length} 行错误。为避免部分数据写入，文件内所有货柜均未录入。</div><div class="import-errors" style="margin-top:16px;max-height:360px;overflow:auto">${errors.map(message=>`<p style="margin:0 0 10px">${esc(message)}</p>`).join("")}</div>`;openModal("导入失败：请修正文件",body,`<button class="btn primary" onclick="App.closeModal()">知道了</button>`);return}data.containers.push(...rows);log("批量导入",`成功 ${rows.length}，失败 0`);save();closeModal();toast(`导入完成：成功录入 ${rows.length} 个货柜`);render()};reader.onerror=()=>toast("文件读取失败，请重新选择 CSV 文件");reader.readAsText(file,"utf-8")}
  function registerWebMCP(){const ctx=document.modelContext;if(!ctx?.registerTool)return;const controller=new AbortController(),tools=[{name:"list_available_slots",title:"查询可预约 Slot",description:"查询指定仓库和日期的预约时间、容量及剩余数量。",inputSchema:{type:"object",properties:{warehouseId:{type:"string"},date:{type:"string"}},required:["warehouseId","date"],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:({warehouseId,date})=>data.slots.filter(s=>s.warehouse===warehouseId&&s.date===date&&s.active).map(s=>({id:s.id,time:s.time,capacity:s.capacity,remaining:remaining(s),dailyRemaining:dailyCap(warehouseId,date)-dailyCount(warehouseId,date),status:remaining(s)>0?"available":"full"}))},{name:"create_container_booking",title:"创建货柜预约",description:"为未预约货柜创建预约；满足 Slot、日总量和客户限额时自动通过，否则进入运营审核。",inputSchema:{type:"object",properties:{containerId:{type:"string"},slotId:{type:"string"}},required:["containerId","slotId"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:({containerId,slotId})=>{const c=container(containerId),s=slot(slotId);if(!c||!s)throw new Error("货柜或 Slot 不存在");if(bookingForContainer(containerId))throw new Error("货柜已有有效预约");const d=capacityDecision(c,s),b={id:`BK-${Date.now()}`,containerId,slotId,status:d.ok?"confirmed":"pending",pendingReason:d.ok?"":d.reason,super:false,createdBy:"WebMCP",createdAt:nowText(),history:[{title:d.ok?"预约自动通过":"提交预约审核",time:nowText(),note:d.reason}]};data.bookings.push(b);save();render();return {id:b.id,status:b.status,reason:d.reason}}}];tools.forEach(t=>Promise.resolve(ctx.registerTool(t,{signal:controller.signal})).catch(()=>{}))}
  window.App={login,logout,go,setFilter,statusMenuToggled,toggleStatus,closeModal,closeDrawer,openAddContainer,addContainer,openBooking,chooseBookingDate,chooseBookingSlot,submitBooking,openDetail,openImport,downloadTemplate,importCsv,openReview,approveBooking,rejectBooking,openReschedule,submitReschedule,acceptReschedule,rejectReschedule,cancelBooking,openAddSlot,renderSlotModal,updateSlotRow,addSlotRow,removeSlotRow,toggleSlotDate,changeSlotMonth,removeSlotDate,addSlots,toggleSlot,openSuperBooking,openSuperList,toggleSuperList,searchSuper,selectSuper,clearSuper,createSuperBooking,markArrived,openComplete,markCompleted,openDay,exportDay,exportMonth,exportTasks,openCustomer,saveCustomer,toggleCustomer,openWarehouse,saveWarehouse,toggleWarehouse,openAccount,saveAccount,toggleAccount};
  $("#mobile-menu").addEventListener("click",()=>$(".sidebar").classList.toggle("open"));$("#modal").addEventListener("click",e=>{if(e.target.id==="modal")closeModal()});$("#drawer").addEventListener("click",e=>{if(e.target.id==="drawer")closeDrawer()});document.addEventListener("click",e=>{if(!e.target.closest?.(".search-wrap")){const box=$("#super-results"),input=$("#super-search");box?.classList.remove("open");input?.setAttribute("aria-expanded","false")}});document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeModal();closeDrawer()}});showLogin();registerWebMCP();
})();
